apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
    - post-delete-finalizer.argocd.argoproj.io
    - post-delete-finalizer.argocd.argoproj.io/cleanup
spec:
  project: default
  source:
    repoURL: https://releases.rancher.com/server-charts/latest
    chart: rancher
    targetRevision: 2.14.1
    helm:
      valuesObject:
        hostname: rancher.localhost
        bootstrapPassword: SuperAdmin@123
        replicas: 1
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "3"
            memory: 4Gi
        startupProbe:
          failureThreshold: 60
          periodSeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 10
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 10
          periodSeconds: 30
          timeoutSeconds: 10
        extraNodeSelectorTerms:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
        extraTolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        ingress:
          tls:
            source: secret
          ingressClassName: nginx
          class: nginx
          extraAnnotations:
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
