---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-server
  namespace: ai-platform
  labels:
    app: embedding-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: embedding-server
  template:
    metadata:
      labels:
        app: embedding-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: llm-data
      containers:
        - name: embeddings
          image: ghcr.io/anasgrt/embedding-server
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: embedding-config
          volumeMounts:
            - name: cache
              mountPath: /models
          resources:
            requests:
              memory: 1024Mi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 1500m
          startupProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 18
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: cache
          hostPath:
            path: /vagrant/prebuilt-models
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: embedding-server
  namespace: ai-platform
  labels:
    app: embedding-server
spec:
  selector:
    app: embedding-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
