apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-analysis-ingress
  namespace: ai-platform
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chat.localhost
      secretName: local-tls-cert
  rules:
    - host: chat.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: log-analysis-app
                port:
                  number: 8000
